apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: backend
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest  # You can specify a specific Redis image version if needed
        ports:
        - containerPort: 6379  # Redis default port
        resources:
          requests:
            memory: "64Mi"  # Adjust resource requests and limits as needed
            cpu: "100m"

