apiVersion: apps/v1
kind: Deployment
metadata:
  name: topstudy
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topstudy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: topstudy
    spec:
      containers:
        - name: topstudy
          image: registry.digitalocean.com/topstudy/topstudy:latest
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 1200m
              memory: 1800Mi

---

apiVersion: v1
kind: Service
metadata:
  name: topstudy
  namespace: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: topstudy
