apiVersion: apps/v1
kind: Deployment
metadata:
 name: web
 namespace: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: registry.digitalocean.com/topstudy/web:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 800Mi

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: web
